### ISSUE TITLE
Embeddings ContextProvider

### ISSUE THREAD

**Issue by sestinj** [continuedev/contribution-ideas#6]
I've started work on this [here](https://github.com/continuedev/continue/blob/main/continuedev/src/continuedev/plugins/context_providers/embeddings.py), but it hasn't been tested thoroughly and could use some user experience improvements / better design decisions.

**Comment by smyja** [comment]
That link isn't working.

**Comment by sestinj** [comment]
Update: this feature has now been shipped: https://continue.dev/docs/walkthroughs/codebase-embeddings
