### ISSUE TITLE
Headless Mode

### ISSUE THREAD

**Issue by sestinj** [continuedev/contribution-ideas#8]
Since Continue is built to work with any IDE, it can also work with _no_ IDE. This would be useful if you want to run tasks in the background, for example from the CLI or in CI/CD.

Implementation of headless mode is complete at a basic level, but there isn't yet a sophisticated CLI application. [Here](https://github.com/continuedev/continue/blob/main/server/continuedev/headless/__init__.py) you can find the beginnings of a simple CLI app, but much more can probably be done, for example:

- allowing more options
- formatting the output more nicely
- developing AI agents that can run in the background in headless mode

**Comment by Sushanti99** [comment]
Hi @sestinj  
I don't think the link above works anymore, could you guide me to where the CLI app init is present?

Also, have we considered employing Langchain in the background for more complicated requests from users?

**Comment by sestinj** [comment]
@Sushanti99 thanks for the heads up, just updated the link. We are currently avoiding LangChain due to the extra size it would add to our binary, but if you're using headless mode it is very possible to just import LangChain separately

**Comment by mathieu-heyarctic** [comment]
An interesting thought would be to export an OpenAI-compatible endpoint so you could consume the continue api through an endpoint definition fully supported by nearly all llm agent implementations. It could make a headless mode a bit less involved.

**Comment by matbee-eth** [comment]
An interesting thought would be to export an OpenAI-compatible endpoint so you could consume the continue api through an endpoint definition fully supported by nearly all llm agent implementations. It could make a headless mode a bit less involved.
