### ISSUE TITLE
Improved Webpage Parsing

### ISSUE THREAD

**Issue by sestinj** [continuedev/contribution-ideas#9]
The current [`DocsContextProvider`](https://github.com/continuedev/continue/blob/preview/core/context/providers/DocsContextProvider.ts) mostly [uses the default from `node-html-markdown](https://github.com/continuedev/continue/blob/preview/core/indexing/docs/urlToMarkdown.ts) to convert HTML to markdown, but this sometimes includes junk, including ads, navigation text, etc... We just want the important content (headers, paragraphs, etc...).

**Comment by barelysomethin** [comment]
hey, hi! how can i know more about this and do we want to shift to a new tool like puppeteer and cheerio  or we just want to change configs of node-html-markdown according to our needs.

**Comment by malaki12003** [comment]
Hey @sestinj, I noticed this ticket is still open and doesn’t seem to be assigned to anyone yet. Would it be alright if I pick it up?
